export { A as AtPromptResponseScore } from './prompt-CQKUaTzD.js';
export { A as AtChartColorPalette } from './chart-color-DTlEjff-.js';
export { a as AtTimeDateUtil, A as AtTimeUnit } from './at-time-date.util-Bfdzn_RG.js';

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:add/16.js
var _16_default$B = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M17 15 17 8 15 8 15 15 8 15 8 17 15 17 15 24 17 24 17 17 24 17 24 15z" }
	}],
	"name": "add",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:arrow--left/16.js
var _16_default$A = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 16 16",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M6.7 12.3 2.9 8.5 15 8.5 15 7.5 2.9 7.5 6.7 3.7 6 3 1 8 6 13z" }
	}],
	"name": "arrow--left",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:arrow--right/16.js
var _16_default$z = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 16 16",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M9.3 3.7 13.1 7.5 1 7.5 1 8.5 13.1 8.5 9.3 12.3 10 13 15 8 10 3z" }
	}],
	"name": "arrow--right",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:arrow--up/16.js
var _16_default$y = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 16 16",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M3.7 6.7 7.5 2.9 7.5 15 8.5 15 8.5 2.9 12.3 6.7 13 6 8 1 3 6z" }
	}],
	"name": "arrow--up",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:delete/16.js
var _16_default$x = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "m29,26H12c-.2651,0-.5195-.1053-.707-.2928L2.293,16.7072c-.3906-.3906-.3906-1.0237,0-1.4143L11.293,6.2928c.1875-.1875.4419-.2928.707-.2928h17c.5522,0,1,.4478,1,1v18c0,.5522-.4478,1-1,1Zm-16.5857-2h15.5857V8h-15.5857l-8,8,8,8Z" }
	}, {
		"elem": "path",
		"attrs": { "d": "M20.4141 16 25 11.4141 23.5859 10 19 14.5859 14.4143 10 13 11.4141 17.5859 16 13 20.5859 14.4143 22 19 17.4141 23.5859 22 25 20.5859 20.4141 16z" }
	}],
	"name": "delete",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:close--filled/16.js
var _16_default$w = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 16 16",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M8,1C4.1,1,1,4.1,1,8s3.1,7,7,7s7-3.1,7-7S11.9,1,8,1z M10.7,11.5L8,8.8l-2.7,2.7l-0.8-0.8L7.2,8L4.5,5.3l0.8-0.8L8,7.2	l2.7-2.7l0.8,0.8L8.8,8l2.7,2.7L10.7,11.5z" }
	}],
	"name": "close--filled",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:caret--down/16.js
var _16_default$v = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M24 12 16 22 8 12z" }
	}],
	"name": "caret--down",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:caret--up/16.js
var _16_default$u = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M8 20 16 10 24 20z" }
	}],
	"name": "caret--up",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:checkmark/16.js
var _16_default$t = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M13 24 4 15 5.414 13.586 13 21.171 26.586 7.586 28 9 13 24z" }
	}],
	"name": "checkmark",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:chevron--down/16.js
var _16_default$s = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 16 16",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M8 11 3 6 3.7 5.3 8 9.6 12.3 5.3 13 6z" }
	}],
	"name": "chevron--down",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:chevron--left/16.js
var _16_default$r = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 16 16",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M5 8 10 3 10.7 3.7 6.4 8 10.7 12.3 10 13z" }
	}],
	"name": "chevron--left",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:chevron--right/16.js
var _16_default$q = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 16 16",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M11 8 6 13 5.3 12.3 9.6 8 5.3 3.7 6 3z" }
	}],
	"name": "chevron--right",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:close/16.js
var _16_default$p = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M17.4141 16 24 9.4141 22.5859 8 16 14.5859 9.4143 8 8 9.4141 14.5859 16 8 22.5859 9.4143 24 16 17.4141 22.5859 24 24 22.5859 17.4141 16z" }
	}],
	"name": "close",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:voice-mode/16.js
var _16_default$o = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M17,29h-2V3h2v26ZM23,6h-2v20h2V6ZM11,6h-2v20h2V6ZM5,11h-2v10h2v-10ZM29,11h-2v10h2.0031s-.0031-10-.0031-10Z" }
	}],
	"name": "voice-mode",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:copy/16.js
var _16_default$n = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M28,10V28H10V10H28m0-2H10a2,2,0,0,0-2,2V28a2,2,0,0,0,2,2H28a2,2,0,0,0,2-2V10a2,2,0,0,0-2-2Z" }
	}, {
		"elem": "path",
		"attrs": { "d": "M4,18H2V4A2,2,0,0,1,4,2H18V4H4Z" }
	}],
	"name": "copy",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:download/16.js
var _16_default$m = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 16 16",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M13 7 12.3 6.3 8.5 10.1 8.5 1 7.5 1 7.5 10.1 3.7 6.3 3 7 8 12z" }
	}, {
		"elem": "path",
		"attrs": { "d": "M13,12v2H3v-2H2v2l0,0c0,0.6,0.4,1,1,1h10c0.6,0,1-0.4,1-1l0,0v-2H13z" }
	}],
	"name": "download",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:edit/16.js
var _16_default$l = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M2 26H30V28H2z" }
	}, {
		"elem": "path",
		"attrs": { "d": "M25.4,9c0.8-0.8,0.8-2,0-2.8c0,0,0,0,0,0l-3.6-3.6c-0.8-0.8-2-0.8-2.8,0c0,0,0,0,0,0l-15,15V24h6.4L25.4,9z M20.4,4L24,7.6	l-3,3L17.4,7L20.4,4z M6,22v-3.6l10-10l3.6,3.6l-10,10H6z" }
	}],
	"name": "edit",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:warning--filled/16.js
var _16_default$k = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 16 16",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M8,1C4.2,1,1,4.2,1,8s3.2,7,7,7s7-3.1,7-7S11.9,1,8,1z M7.5,4h1v5h-1C7.5,9,7.5,4,7.5,4z M8,12.2	c-0.4,0-0.8-0.4-0.8-0.8s0.3-0.8,0.8-0.8c0.4,0,0.8,0.4,0.8,0.8S8.4,12.2,8,12.2z" }
	}, {
		"elem": "path",
		"attrs": {
			"d": "M7.5,4h1v5h-1C7.5,9,7.5,4,7.5,4z M8,12.2c-0.4,0-0.8-0.4-0.8-0.8s0.3-0.8,0.8-0.8	c0.4,0,0.8,0.4,0.8,0.8S8.4,12.2,8,12.2z",
			"data-icon-path": "inner-path",
			"opacity": "0"
		}
	}],
	"name": "warning--filled",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:arrange/16.js
var _16_default$j = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M30,29H2v-2h28v2ZM27,19H5v2h22v-2ZM24,11H8v2h16v-2ZM21,3h-10v2h10v-2Z" }
	}],
	"name": "arrange",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:page--first/16.js
var _16_default$i = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M14 16 24 6 25.4 7.4 16.8 16 25.4 24.6 24 26z" }
	}, {
		"elem": "path",
		"attrs": { "d": "M8 4H10V28H8z" }
	}],
	"name": "page--first",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:help/16.js
var _16_default$h = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 16 16",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [
		{
			"elem": "path",
			"attrs": { "d": "M8,1C4.1,1,1,4.1,1,8s3.1,7,7,7s7-3.1,7-7S11.9,1,8,1z M8,14c-3.3,0-6-2.7-6-6s2.7-6,6-6s6,2.7,6,6S11.3,14,8,14z" }
		},
		{
			"elem": "circle",
			"attrs": {
				"cx": "8",
				"cy": "11.8",
				"r": ".8"
			}
		},
		{
			"elem": "path",
			"attrs": { "d": "M8.5,4H7.8C6.5,4,5.5,5,5.5,6.2c0,0,0,0,0,0v0.2h1V6.2C6.5,5.6,7.1,5,7.8,5h0.8c0.7,0,1.2,0.6,1.2,1.2S9.2,7.5,8.5,7.5h-1	v2.2h1V8.5c1.2,0,2.2-1,2.2-2.2S9.7,4,8.5,4z" }
		}
	],
	"name": "help",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:information/16.js
var _16_default$g = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 16 16",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [
		{
			"elem": "path",
			"attrs": { "d": "M8.5 11 8.5 6.5 6.5 6.5 6.5 7.5 7.5 7.5 7.5 11 6 11 6 12 10 12 10 11z" }
		},
		{
			"elem": "path",
			"attrs": { "d": "M8,3.5c-0.4,0-0.8,0.3-0.8,0.8S7.6,5,8,5c0.4,0,0.8-0.3,0.8-0.8S8.4,3.5,8,3.5z" }
		},
		{
			"elem": "path",
			"attrs": { "d": "M8,15c-3.9,0-7-3.1-7-7s3.1-7,7-7s7,3.1,7,7S11.9,15,8,15z M8,2C4.7,2,2,4.7,2,8s2.7,6,6,6s6-2.7,6-6S11.3,2,8,2z" }
		}
	],
	"name": "information",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:information--filled/16.js
var _16_default$f = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": {
			"fill": "none",
			"d": "M16,8a1.5,1.5,0,1,1-1.5,1.5A1.5,1.5,0,0,1,16,8Zm4,13.875H17.125v-8H13v2.25h1.875v5.75H12v2.25h8Z",
			"data-icon-path": "inner-path"
		}
	}, {
		"elem": "path",
		"attrs": { "d": "M16,2A14,14,0,1,0,30,16,14,14,0,0,0,16,2Zm0,6a1.5,1.5,0,1,1-1.5,1.5A1.5,1.5,0,0,1,16,8Zm4,16.125H12v-2.25h2.875v-5.75H13v-2.25h4.125v8H20Z" }
	}],
	"name": "information--filled",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:page--last/16.js
var _16_default$e = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M18 16 8 26 6.6 24.6 15.2 16 6.6 7.4 8 6z" }
	}, {
		"elem": "path",
		"attrs": { "d": "M22 4H24V28H22z" }
	}],
	"name": "page--last",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:overflow-menu--vertical/16.js
var _16_default$d = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [
		{
			"elem": "circle",
			"attrs": {
				"cx": "16",
				"cy": "8",
				"r": "2"
			}
		},
		{
			"elem": "circle",
			"attrs": {
				"cx": "16",
				"cy": "16",
				"r": "2"
			}
		},
		{
			"elem": "circle",
			"attrs": {
				"cx": "16",
				"cy": "24",
				"r": "2"
			}
		}
	],
	"name": "overflow-menu--vertical",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:watson-health/rotate--360/16.js
var _16_default$c = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M25.95,7.65l.0047-.0039c-.0918-.1094-.197-.2061-.2925-.3125-.1841-.2051-.3672-.41-.5635-.603-.1382-.1358-.2856-.2613-.43-.3907-.1831-.1645-.3657-.3286-.5581-.4824-.1592-.1279-.3244-.2466-.4895-.3667-.1921-.14-.3855-.2768-.5854-.4062-.1743-.1128-.3523-.2188-.5322-.3238q-.3081-.1786-.6253-.3408c-.1846-.0942-.37-.1846-.56-.27-.2224-.1-.449-.1914-.678-.2793-.1894-.0723-.3777-.1455-.5713-.209-.2463-.0815-.498-.1494-.7507-.2163-.1848-.0493-.3674-.1025-.5554-.1431-.29-.0634-.5865-.1074-.8833-.1508-.159-.023-.3145-.0552-.4754-.0728A12.9331,12.9331,0,0,0,6,7.7031V4H4v8h8V10H6.8115A10.961,10.961,0,0,1,16,5a11.1114,11.1114,0,0,1,1.189.0669c.1362.0146.268.042.4026.0615.2509.0366.5014.0742.7468.1275.1592.0346.3144.08.4712.1215.2131.0562.4258.1138.6335.1822.1643.0547.325.1167.4859.1782.1926.0742.3835.1509.5705.2349.1611.0727.3193.15.4763.23q.2677.1363.5262.2867c.153.0893.3046.18.4531.2758.1679.1089.3308.2242.4922.3413.1406.1026.2817.2037.417.3125.1616.1294.3156.2676.47.4063.1225.11.2478.2168.3652.332.1668.1636.3223.3379.4785.5117A10.9928,10.9928,0,1,1,5,16H3A13,13,0,1,0,25.95,7.65Z" }
	}],
	"name": "rotate--360",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:event--schedule/16.js
var _16_default$b = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [
		{
			"elem": "path",
			"attrs": { "d": "M21,30a8,8,0,1,1,8-8A8,8,0,0,1,21,30Zm0-14a6,6,0,1,0,6,6A6,6,0,0,0,21,16Z" }
		},
		{
			"elem": "path",
			"attrs": { "d": "M22.59 25 20 22.41 20 18 22 18 22 21.59 24 23.59 22.59 25z" }
		},
		{
			"elem": "path",
			"attrs": { "d": "M28,6a2,2,0,0,0-2-2H22V2H20V4H12V2H10V4H6A2,2,0,0,0,4,6V26a2,2,0,0,0,2,2h4V26H6V6h4V8h2V6h8V8h2V6h4v6h2Z" }
		}
	],
	"name": "event--schedule",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:search/16.js
var _16_default$a = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 16 16",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M15,14.3L10.7,10c1.9-2.3,1.6-5.8-0.7-7.7S4.2,0.7,2.3,3S0.7,8.8,3,10.7c2,1.7,5,1.7,7,0l4.3,4.3L15,14.3z M2,6.5	C2,4,4,2,6.5,2S11,4,11,6.5S9,11,6.5,11S2,9,2,6.5z" }
	}],
	"name": "search",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:stop--filled--alt/16.js
var _16_default$9 = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M24,6H8A2,2,0,0,0,6,8V24a2,2,0,0,0,2,2H24a2,2,0,0,0,2-2V8a2,2,0,0,0-2-2Z" }
	}],
	"name": "stop--filled--alt",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:subtract/16.js
var _16_default$8 = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M8 15H24V17H8z" }
	}],
	"name": "subtract",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:checkmark--filled/16.js
var _16_default$7 = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 16 16",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M8,1C4.1,1,1,4.1,1,8c0,3.9,3.1,7,7,7s7-3.1,7-7C15,4.1,11.9,1,8,1z M7,11L4.3,8.3l0.9-0.8L7,9.3l4-3.9l0.9,0.8L7,11z" }
	}, {
		"elem": "path",
		"attrs": {
			"d": "M7,11L4.3,8.3l0.9-0.8L7,9.3l4-3.9l0.9,0.8L7,11z",
			"data-icon-path": "inner-path",
			"opacity": "0"
		}
	}],
	"name": "checkmark--filled",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:thumbs-down/16.js
var _16_default$6 = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M30,16V9a7.0078,7.0078,0,0,0-7-7H2V16H8.4648l3.5774,5.3662.8453,5.9165A2.0094,2.0094,0,0,0,14.8672,29H17a3.0033,3.0033,0,0,0,3-3V20h6A4.0045,4.0045,0,0,0,30,16ZM8,14H4V4H8Zm20,2a2.0025,2.0025,0,0,1-2,2H18v8a1.0008,1.0008,0,0,1-1,1H14.8672l-.9094-6.3662L10,14.6973V4H23a5.0057,5.0057,0,0,1,5,5Z" }
	}],
	"name": "thumbs-down",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:thumbs-down--filled/16.js
var _16_default$5 = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M2 2H7V16H2z" }
	}, {
		"elem": "path",
		"attrs": { "d": "M23,2H9V16.8027l3.0422,4.5635.8453,5.9165A2.0094,2.0094,0,0,0,14.8672,29H15a3.0033,3.0033,0,0,0,3-3V20h8a4.0045,4.0045,0,0,0,4-4V9A7.0078,7.0078,0,0,0,23,2Z" }
	}],
	"name": "thumbs-down--filled",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:thumbs-up/16.js
var _16_default$4 = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M26,12H20V6a3.0033,3.0033,0,0,0-3-3H14.8672a2.0094,2.0094,0,0,0-1.98,1.7173l-.8453,5.9165L8.4648,16H2V30H23a7.0078,7.0078,0,0,0,7-7V16A4.0045,4.0045,0,0,0,26,12ZM8,28H4V18H8Zm20-5a5.0057,5.0057,0,0,1-5,5H10V17.3027l3.9578-5.9365L14.8672,5H17a1.0008,1.0008,0,0,1,1,1v8h8a2.0025,2.0025,0,0,1,2,2Z" }
	}],
	"name": "thumbs-up",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:thumbs-up--filled/16.js
var _16_default$3 = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M2 16H7V30H2z" }
	}, {
		"elem": "path",
		"attrs": { "d": "M23,30H9V15.1973l3.0422-4.5635.8453-5.9165A2.0094,2.0094,0,0,1,14.8672,3H15a3.0033,3.0033,0,0,1,3,3v6h8a4.0045,4.0045,0,0,1,4,4v7A7.0078,7.0078,0,0,1,23,30Z" }
	}],
	"name": "thumbs-up--filled",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:warning--alt--filled/16.js
var _16_default$2 = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [
		{
			"elem": "path",
			"attrs": {
				"fill": "none",
				"d": "M16,26a1.5,1.5,0,1,1,1.5-1.5A1.5,1.5,0,0,1,16,26Zm-1.125-5h2.25V12h-2.25Z",
				"data-icon-path": "inner-path"
			}
		},
		{
			"elem": "path",
			"attrs": { "d": "M16.002,6.1714h-.004L4.6487,27.9966,4.6506,28H27.3494l.0019-.0034ZM14.875,12h2.25v9h-2.25ZM16,26a1.5,1.5,0,1,1,1.5-1.5A1.5,1.5,0,0,1,16,26Z" }
		},
		{
			"elem": "path",
			"attrs": { "d": "M29,30H3a1,1,0,0,1-.8872-1.4614l13-25a1,1,0,0,1,1.7744,0l13,25A1,1,0,0,1,29,30ZM4.6507,28H27.3493l.002-.0033L16.002,6.1714h-.004L4.6487,27.9967Z" }
		}
	],
	"name": "warning--alt--filled",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:side-panel--open/16.js
var _16_default$1 = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M28,4H4C2.9,4,2,4.9,2,6v20c0,1.1,0.9,2,2,2h24c1.1,0,2-0.9,2-2V6C30,4.9,29.1,4,28,4z M10,26H4V6h6V26z M28,26H12v-9h10.2	l-3.6,3.6L20,22l6-6l-6-6l-1.4,1.4l3.6,3.6H12V6h16V26z" }
	}],
	"name": "side-panel--open",
	"size": 16
};

/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */
//#region virtual:side-panel--close/16.js
var _16_default = {
	"elem": "svg",
	"attrs": {
		"xmlns": "http://www.w3.org/2000/svg",
		"viewBox": "0 0 32 32",
		"fill": "currentColor",
		"width": 16,
		"height": 16
	},
	"content": [{
		"elem": "path",
		"attrs": { "d": "M28,4H4C2.9,4,2,4.9,2,6v20c0,1.1,0.9,2,2,2h24c1.1,0,2-0.9,2-2V6C30,4.9,29.1,4,28,4z M10,26H4V6h6V26z M28,15H17.8	l3.6-3.6L20,10l-6,6l6,6l1.4-1.4L17.8,17H28v9H12V6h16V15z" }
	}],
	"name": "side-panel--close",
	"size": 16
};

const ATUI_ICONS = [
    { name: 'add', icon: _16_default$B },
    { name: 'arrow_left', icon: _16_default$A },
    { name: 'arrow_right', icon: _16_default$z },
    { name: 'arrow_up', icon: _16_default$y },
    { name: 'backspace', icon: _16_default$x },
    { name: 'cancel', icon: _16_default$w },
    { name: 'caret_down', icon: _16_default$v },
    { name: 'caret_up', icon: _16_default$u },
    { name: 'checkmark', icon: _16_default$t },
    { name: 'chevron_down', icon: _16_default$s },
    { name: 'chevron_left', icon: _16_default$r },
    { name: 'chevron_right', icon: _16_default$q },
    { name: 'close', icon: _16_default$p },
    { name: 'column', icon: _16_default$o },
    { name: 'copy', icon: _16_default$n },
    { name: 'download', icon: _16_default$m },
    { name: 'edit', icon: _16_default$l },
    { name: 'error', icon: _16_default$k },
    { name: 'filter_list', icon: _16_default$j },
    { name: 'first_page', icon: _16_default$i },
    { name: 'help', icon: _16_default$h },
    { name: 'info', icon: _16_default$g },
    { name: 'info_filled', icon: _16_default$f },
    { name: 'last_page', icon: _16_default$e },
    { name: 'menu_expand', icon: _16_default$1 },
    { name: 'menu_collapse', icon: _16_default },
    { name: 'overflow_menu', icon: _16_default$d },
    { name: 'retry', icon: _16_default$c },
    { name: 'schedule', icon: _16_default$b },
    { name: 'search', icon: _16_default$a },
    { name: 'stop', icon: _16_default$9 },
    { name: 'subtract', icon: _16_default$8 },
    { name: 'success', icon: _16_default$7 },
    { name: 'thumbs_down', icon: _16_default$6 },
    { name: 'thumbs_down_filled', icon: _16_default$5 },
    { name: 'thumbs_up', icon: _16_default$4 },
    { name: 'thumbs_up_filled', icon: _16_default$3 },
    { name: 'warning', icon: _16_default$2 },
];

const DEFAULT_TOAST_OPTIONS = {
    position: 'bottom-right',
    timeout: 5000,
    dismissible: true,
    closeButton: false,
};

class ToasterService {
    static id = 0;
    static containers = new Map();
    /**
     * Show a toast message
     *
     * @param type The type of the toast
     * @param message The message to display in the toast
     * @param options Additional options for the toast (title, position, timeout, dismissible)
     */
    static async show(type, message, options = {}) {
        const id = this.id++;
        const toastOptions = {
            ...DEFAULT_TOAST_OPTIONS,
            ...options,
        };
        const toast = { id, type, message, ...toastOptions };
        const toaster = await this.getToaster(toastOptions.position);
        toaster.addToast(toast);
    }
    /**
     * Get or create at-toaster component
     * Waits for the element to be upgraded and hydrated before returning.
     * Stores the toaster container with position in the Map
     */
    static async getToaster(position) {
        if (this.containers.has(position)) {
            const existing = this.containers.get(position);
            if (existing &&
                document.body.contains(existing)) {
                return existing;
            }
            this.containers.delete(position);
        }
        const el = document.createElement('at-toaster');
        el.setAttribute('position', position);
        document.body.appendChild(el);
        await customElements.whenDefined('at-toaster');
        const stencilEl = el;
        if (typeof stencilEl.componentOnReady === 'function') {
            await stencilEl.componentOnReady();
        }
        const toasterEl = el;
        this.containers.set(position, toasterEl);
        return toasterEl;
    }
}

export { ATUI_ICONS, ToasterService };
