import type { Meta, StoryObj } from '@storybook/web-components';
declare const meta: Meta;
export default meta;
type Story = StoryObj;
export declare const Default: Story;
export declare const WithLabel: Story;
export declare const LargeTextarea: Story;
export declare const WithCharacterLimit: Story;
export declare const WithError: Story;
export declare const Disabled: Story;
export declare const InProgress: Story;
