import type { Meta, StoryObj } from '@storybook/web-components';
declare const meta: Meta;
export default meta;
type Story = StoryObj;
export declare const Empty: Story;
export declare const WithMessages: Story;
export declare const WithLoading: Story;
export declare const WithError: Story;
export declare const ShortContainer: Story;
export declare const SystemMessages: Story;
export declare const CustomEmptyState: Story;
